# Generated by Django 5.0.6 on 2024-07-05 05:29

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='f_pago',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]