# Generated by Django 5.0.6 on 2024-07-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pago_fecha_pago_pago_f_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
    ]
